### ISSUE TITLE
Cannot run on macOS.

### ISSUE THREAD

**Issue by AsaMitakaIT** [TheLastGimbus/easydrop#3]
Missing **systemctl**, **ip**, and **iw** commands. In fact, I hope to directly accept Airdrop from any Apple device, which must be manually confirmed on macOS.

**Comment by TheLastGimbus** [comment]
oh sorry but this is loooong forgotten script

i think owl, which it bases on, stopped working stable, and many ios updates came out in time...

good luck with that tho!
